---
- name: Update Pip to latest Version
  pip:
    name: pip
    state: latest

- name: Install GitHub Python Package
  pip:
    name: github3.py >= 1.0.0a3
    state: present
    executable: /usr/local/bin/pip3

- name: Grab latest CircleCI CLI Version
  github_release:
    user: CircleCI-Public
    repo: circleci-cli
    action: latest_release
  register: github_response

- name: Set Latest Version of CLI
  set_fact:
    latest_version: "{{ github_response.tag[1:] }}"

- name: Check if Version is Set
  set_fact:
    CLI_VERSION: "{{ latest_version }}"
  when: CLI_VERSION == None  

- name: Format Architecture Name - x86_64 to amd64
  set_fact:
    arch: "amd64"
  when:  ansible_architecture == 'x86_64'

- name: Format Architecture Name - aarch64 to arm64
  set_fact:
    arch: "arm64"
  when:  ansible_architecture == 'aarch64'

- name: Format Architecture Name - Other Architectures
  set_fact:
    arch: "{{ ansible_architecture }}"
  when: ansible_architecture != 'x86_64' and ansible_architecture != 'aarch64'

- name: Install CircleCI CLI for Linux
  include_tasks: linux-setup.yml
  when: ansible_system == "Linux"

# - name: Install CircleCI CLI for Windows
#   include_tasks: windows-setup.yml
#   when: ansible_system == "Win32NT"

- name: Install CircleCI CLI for MacOS
  include_tasks: darwin-setup.yml
  when: ansible_system == "Darwin" 
