version: 2.1

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - lint:
          requires:
            - build
      - deploy:
          requires: 
            - lint
          filters:
            branches:
              only: main


jobs:
  build:
    docker:
      - image: cimg/node:15.6.0
    steps:
      - checkout
      - run: 
          name: Node Version
          command: node --version
      - restore_cache:
          keys: 
            - dependency-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - dependency-cache-{{ .Branch }}
      - run: 
          name: NPM Install
          command: npm install 
      - save_cache:
          paths:
            - ./node_modules
          key: dependency-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: 
          name: Run Tests
          command: npm test
  lint: 
    docker:
      - image: cimg/node:15.6.0
    steps:
      - checkout 
      - run: 
          name: Node Version
          command: node --version
      - restore_cache:
          keys: 
            - dependency-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - dependency-cache-{{ .Branch }}
      - run: 
          name: NPM Install
          command: npm install 
      - save_cache:
          paths:
            - ./node_modules
          key: dependency-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Run Linting
          command: npm run lint
  deploy:
    docker:
      - image: cimg/node:15.6.0
    steps:
      - checkout 
      - run: 
          name: Deploy Main To Heroku
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main