version: 2.1
#reusable executors: define build environment (container or vm) that can be used to run any job(s) in this config
executors:
  my-executor:
     docker:
      - image: cimg/node:15.6.0

orbs:
  heroku: circleci/heroku@1.2.6

#orchestrate jobs: define dependencies, run order, and approval 
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - lint
            - test
          filters: 
            branches:
              only: main
      - heroku/deploy-via-git:
          requires: 
            - hold
          filters:
            branches:
              only: main

# reusable commands: can be called as steps in any job(s) in this config
commands:
  installnode:
    description: "Install and cache node"
    steps:
      - checkout
      - run: 
          name: Node Version
          command: node --version
      - restore_cache:
          keys: 
            - dependency-cache-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - dependency-cache-v1-{{ .Branch }}
      - run: 
          name: NPM Install
          command: npm install --legacy-peer-deps  
      - save_cache:
          paths:
            - ./node_modules
          key: dependency-cache-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}  
# builing blocks of ci/cd
jobs:
  build:
    executor: my-executor
    steps:
      - installnode
  lint: 
    executor: my-executor
    steps:
      - installnode
      - run:
          name: Run Linting
          command: npm run lint
  test: 
    parallelism: 2
    executor: my-executor
    steps:
      - installnode 
      - run: npm run coverage
      - run: 
          name: Run Tests
          command: |
            TEST=$(circleci tests glob **/__tests__/*.js | circleci tests split --split-by=timings)
            npm test $TEST
      - store_test_results:
          path: ~/coverage
  

  # REPLACED code with orb
  # deploy:
  #   executor: my-executor
  #   steps:
  #     - checkout 
  #     - run: 
  #         name: Deploy Main To Heroku
  #         command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main