version: 2.1

executors:
  my-executor:
     docker:
      - image: cimg/node:15.6.0

orbs:
  heroku: circleci/heroku@1.2.6

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
          jobs:
            - printstep:
               printname: BUILD
      - lint:
          requires:
            - build
          jobs:
            - printstep:
                printname: LINT
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - lint
            - test
      - heroku/deploy-via-git:
          requires: 
            - hold
          filters:
            branches:
              only: main

commands:
  installnode:
    description: "Install and cache node"
    steps:
      - checkout
      - run: 
          name: Node Version
          command: node --version
      - restore_cache:
          keys: 
            - dependency-cache-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - dependency-cache-v1-{{ .Branch }}
      - run: 
          name: NPM Install
          command: npm install --legacy-peer-deps  
      - save_cache:
          paths:
            - ./node_modules
          key: dependency-cache-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}  

jobs:
  printstep:
    description: A minimial job to echo the name of the step in order to demonstrate what a parameterized job looksl ike
    parameters:
      printname:
        description: "What job is this?"
        default: "Build"
        type: string
    executor: my-executor
    steps:
      - run: echo "This is the step << parameters.stepname >>"
  build:
    executor: my-executor
    steps:
      - installnode
  lint: 
    executor: my-executor
    steps:
      - installnode
      - run:
          name: Run Linting
          command: npm run lint
  test: 
    executor: my-executor
    steps:
      - installnode 
      - run: 
          name: Run Tests
          command: npm test   

  # REPLACED code with orb
  # deploy:
  #   executor: my-executor
  #   steps:
  #     - checkout 
  #     - run: 
  #         name: Deploy Main To Heroku
  #         command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main