CLI_INSTALL_DIR: "/usr/local/bin"
CLI_USER: "{{ ansible_env.SUDO_USER | default(ansible_env.USER, true) | default(ansible_user_id, true) }}"

NAMESPACE_CREATION: false
RESOURCE_CLASS_CREATION: true
RUNNER_TOKEN_CREATION: true

# Only Set Auth Token if RUNNER_TOKEN_CREATION is False
#AUTH_TOKEN:

VCS_TYPE: "github"

NAMESPACE: 
ORG_NAME: 
RESOURCE_CLASS: 
RESOURCE_CLASS_DESCRIPTION: 

API_TOKEN: 

target_hosts: 